profile page
Team-Engineers/CUET pull request #6
Opened 2024-02-12 06:25 UTC by Dev967

## Current functionality:

- All input fields are static, no validation
- Responsive design
- Button for 'Membership' does not work

## Future Scope:
- Input validation
- Packages modal popup on clicking 'Membership' button

2024-02-12 06:27 UTC, Dev967 commented
- put a max width on larger screens, try '2xl:max-w-[80vw]'
- Increase width of input fields
- Increase vertical spacing between input fields
- Center content
- Profile image should be aligned with 'Personal Information' line and should not go above that
- Increase font size of back icon and 'Profile' text at top, also put an underline on that as shown in design
- Font color in input fields should be gray not black, refer design on figma
- Increase the trigger for responsiveness, in tablet(md or lg) screens inputs fields become small and there is way more space left above and below them, try to put everything in column from this breakpoint

responsive design looks great, good job :+1:

2024-02-12 15:57 UTC, TheLeftyCoder requested changes

2024-02-12 15:57 UTC, TheLeftyCoder commented on src/components/profile/ProfileCard.jsx
> +                type="number"
date of birth ke type mein date hona chhaiye, number nhi,  or email jo input le rhe hai, usko validate to krna hoga, valid hai ya wrong, same for phone number validate for 10 digits or 12 digits

![image](https://github.com/Team-Engineers/CUET/assets/106524453/c4c870fa-ac91-454d-a27f-fa4ecdfa2afe)

or sir yeh thoda align nhi hai, same in profile button usmein bhi flex nhi lga hai

2024-02-14 09:06 UTC, TheLeftyCoder requested changes
![image](https://github.com/Team-Engineers/CUET/assets/106524453/4f10c54b-dbd7-4594-b611-bffcac28b9d0)

omkar sir, user input should be in two column, not in one column, please check figma once

2024-02-15 06:25 UTC, merged